---
Name: grouped-reports
After: silvershop-config
---

SilverStripe\Reports\ReportAdmin:
  extensions:
  - ReportsExtension
SilverStripe\CMS\Reports\BrokenLinksReport:
  extensions:
  - ReportsExtraExtension
SilverShop\Reports\SideReport\ShopPeriodReport:
  extensions:
  - ReportsShopExtension